services:
  - type: web
    name: chuveiro-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:$PORT src.main:app"
    envVars:
      - key: FLASK_ENV
        value: production
